# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

# 초단기실황 조회 (실황만)
GET http://127.0.0.1:8000/weather/current?nx=55&ny=127
Accept: application/json

###

# 초단기실황 + 초단기예보 통합 조회
GET http://127.0.0.1:8000/weather/current?nx=55&ny=127&include_forecast=true
Accept: application/json

###

# 서울 시청 날씨 (실황만)
GET http://127.0.0.1:8000/weather/current?nx=60&ny=127
Accept: application/json

###

# 서울 시청 날씨 (실황 + 예보)
GET http://127.0.0.1:8000/weather/current?nx=60&ny=127&include_forecast=true
Accept: application/json

###

# 부산 시청 날씨 (실황 + 예보)
GET http://127.0.0.1:8000/weather/current?nx=98&ny=76&include_forecast=true
Accept: application/json

###

# 특정 날짜/시간 조회 (실황 + 예보)
GET http://127.0.0.1:8000/weather/current?nx=55&ny=127&base_date=20251124&base_time=0630&include_forecast=true
Accept: application/json

###

# 단기예보 조회 (3일 예보)
GET http://127.0.0.1:8000/weather/forecast?nx=55&ny=127
Accept: application/json

###

# 서울 시청 단기예보
GET http://127.0.0.1:8000/weather/forecast?nx=60&ny=127
Accept: application/json

###

# 부산 시청 단기예보
GET http://127.0.0.1:8000/weather/forecast?nx=98&ny=76
Accept: application/json

###

# 특정 발표 시각 단기예보 조회
GET http://127.0.0.1:8000/weather/forecast?nx=55&ny=127&base_date=20251123&base_time=2300
Accept: application/json

###
